# Generated by Django 3.2.3 on 2021-05-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='project',
            index_together={('id', 'slug')},
        ),
    ]
